// Generated by scripts/gen-version.ts from apps/mcp-server/package.json.
// Do not edit by hand — run `pnpm run gen`. Verified in CI by `pnpm run check:gen`.

/** The server's own version, reported by get_rack_status and in the MCP handshake. */
export const SERVER_VERSION = "0.1.0";
