/**
 * Generates docs/architecture/contract-census.md from the live census.
 *
 * The numbers in this document are the reason it is generated: an audit that
 * hand-counts its own coverage goes stale silently, and a stale count is worse
 * than none because it reads as a measurement.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { CENSUS_EXCEPTIONS, describe, runCensus } from "../tests/contract/src/census.js";
import { declaredSymbols } from "../tests/contract/src/declared.js";
import { alwaysConstantKeys, keyProducers } from "../tests/contract/src/producers.js";
import { loadDocs } from "../tests/contract/src/docs.js";
import { loadSources, SOURCE_ROOTS } from "../tests/contract/src/sources.js";

const root = fileURLToPath(new URL("..", import.meta.url));

const results = runCensus();
const declared = declaredSymbols();
const byKind = new Map<string, number>();
for (const d of declared) byKind.set(d.kind, (byKind.get(d.kind) ?? 0) + 1);

const debts = CENSUS_EXCEPTIONS.filter((e) => e.reason.startsWith("TODO:"));
const settled = CENSUS_EXCEPTIONS.filter((e) => !e.reason.startsWith("TODO:"));

const out: string[] = [];
const P = (...lines: string[]) => out.push(...lines);

P(
  "# Contract census",
  "",
  "> Generated by `scripts/gen-census.ts` from the gates in `tests/contract`.",
  "> Do not edit by hand — re-run `pnpm run gen`.",
  "",
  "Every symbol this codebase publishes to a client — an error code, a risk flag, a",
  "limit, a schema property — is a promise. This census fails the build when a promise",
  "has no implementation behind it and no stated reason for standing alone.",
  "",
  "## Surface",
  "",
  "| Declared kind | Count |",
  "| --- | ---: |",
);
for (const [kind, count] of [...byKind].sort()) P(`| ${kind} | ${count} |`);
P(
  `| **total** | **${declared.length}** |`,
  "",
  `Scanned across ${SOURCE_ROOTS.length} source roots and ${loadSources().length} files,`,
  `plus ${loadDocs().length} documentation files and ${keyProducers().length} distinct JSON keys`,
  "emitted by the plugin.",
  "",
  "## Outstanding debts",
  "",
);
if (debts.length === 0) {
  P("None. Every published symbol has an implementation or a settled disposition.", "");
} else {
  P(
    `${debts.length} published symbols are declared ahead of their implementation.`,
    "",
    "| Symbol | Kind | Owed |",
    "| --- | --- | --- |",
  );
  for (const e of [...debts].sort((a, b) => a.symbol.localeCompare(b.symbol))) {
    P(`| \`${e.symbol}\` | ${e.kind} | ${e.reason.replace(/^TODO: /, "").replace(/\|/g, "\\|")} |`);
  }
  P("");
}

P("## Settled dispositions", "");
if (settled.length === 0) {
  P("None.", "");
} else {
  P(
    "These have no implementation reference and are not going to get one. Each states why",
    "it is published anyway.",
    "",
    "| Symbol | Kind | Disposition | Reason |",
    "| --- | --- | --- | --- |",
  );
  for (const e of [...settled].sort((a, b) => a.symbol.localeCompare(b.symbol))) {
    P(
      `| \`${e.symbol}\` | ${e.kind} | ${e.disposition} | ${e.reason.replace(/\|/g, "\\|")} |`,
    );
  }
  P("");
}

P(
  "## Always-constant fields",
  "",
  `${alwaysConstantKeys().length} of the ${keyProducers().length} JSON keys the plugin emits can`,
  "only ever carry one value. A token scan cannot see this, because the key literal is",
  "present either way; the gate matches the jansson call shape instead.",
  "",
  "| Field | Value | Emitted at |",
  "| --- | --- | --- |",
);
for (const p of alwaysConstantKeys()) {
  const site = p.sites.map((s) => `\`${s.file}:${s.line}\``).join(", ");
  P(`| \`${p.key}\` | \`${p.sites[0]?.literal ?? "?"}\` | ${site} |`);
}

P(
  "",
  "## What these gates do not cover",
  "",
  "Stated so the census is not read as a stronger claim than it is.",
  "",
  "- **Reachability.** A symbol named inside an unreachable branch counts as implemented.",
  "  Most sharply: a value named only in the code that *refuses* it passes. `duplicate_module`",
  "  satisfies the census today entirely on the strength of the error message rejecting it.",
  "- **Constancy beyond one syntactic form.** The constant-field gate reads single-line",
  "  `json_object_set_new(obj, \"key\", json_true())` calls. A field built across lines, through",
  "  a helper, or with `json_object_set`, is invisible to it.",
  "- **Semantic truth.** The gates check that a symbol is named somewhere, never that what is",
  "  said about it is true. A description can be confidently wrong and pass everything here.",
  "- **Client-side consumption.** The consumer of an error code or a risk flag is the LLM",
  "  client, outside this repo. The census cannot require a consumer for these, only a producer —",
  "  so a flag that is emitted and universally ignored still passes.",
  "- **Producer drift.** Whether the plugin still emits what the frozen fixtures record is",
  "  mostly a different gate (`tests/integration` capture `--verify`), and mostly needs a live",
  "  Rack. The exception is a producer extracted into Rack-free `core/`, which `tests/cpp` can",
  "  compare against the captured bytes directly -- `buildChatPollPayload` against",
  "  `tests/fixtures/bridge/chat.poll.json` is the one that does. Extraction is what buys the",
  "  static check; the census itself still cannot make it.",
  "- **Non-macOS runtime behaviour.** Everything here is static analysis. It says nothing about",
  "  what the plugin does when it runs, on any platform.",
  "",
  "Comment stripping is applied before every scan so that a comment naming a symbol cannot",
  "stand in for an implementation. On the current tree it changes no verdict — it is there to",
  "keep a future comment from silently satisfying the gate, not because it is load-bearing today.",
  "",
);

const orphans = results.filter((r) => !r.implemented && !r.exception);
if (orphans.length) {
  throw new Error(
    `census is red; refusing to write a document claiming otherwise.\n` +
      orphans.map((o) => `  ${describe(o)}`).join("\n"),
  );
}

writeFileSync(join(root, "docs/architecture/contract-census.md"), out.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n");
console.error(
  `wrote docs/architecture/contract-census.md (${declared.length} declared, ${debts.length} debts, ${settled.length} settled)`,
);
