/**
 * Generates apps/mcp-server/src/version.ts from the server's package.json.
 *
 * The version was written out twice — once in package.json and once as a string
 * literal in server.ts — and a `define` in bundle.mjs claimed to inject it at
 * build time. It did not: the built bundle contains zero occurrences of
 * RACKMCP_SERVER_VERSION, because the source never read that variable. So
 * `get_rack_status` could report a version the package had not been at for
 * some time, and the rollback procedure told operators to verify a rollback by
 * echoing an environment variable nothing consumes.
 *
 * Generating the file, and diffing it in check:gen, makes the drift impossible
 * rather than unlikely.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const pkgPath = join(root, "apps/mcp-server/package.json");
const pkg = JSON.parse(readFileSync(pkgPath, "utf8")) as { version?: unknown };

if (typeof pkg.version !== "string" || !/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(pkg.version)) {
  throw new Error(`apps/mcp-server/package.json has no usable semver version: ${String(pkg.version)}`);
}

const out = `// Generated by scripts/gen-version.ts from apps/mcp-server/package.json.
// Do not edit by hand — run \`pnpm run gen\`. Verified in CI by \`pnpm run check:gen\`.

/** The server's own version, reported by get_rack_status and in the MCP handshake. */
export const SERVER_VERSION = ${JSON.stringify(pkg.version)};
`;

const target = join(root, "apps/mcp-server/src/version.ts");
writeFileSync(target, out);
console.error(`wrote apps/mcp-server/src/version.ts (${pkg.version})`);
